from flask import Flask, jsonify
import random

app = Flask(__name__)

# Lista de fatos sobre Star Wars
facts = [
   "Darth Vader é pai de Luke Skywalker.",
    "Yoda viveu por mais de 900 anos.",
    "O sabre de luz azul é tradicionalmente usado por Jedi.",
    "A Estrela da Morte tinha capacidade para destruir planetas.",
    "Chewbacca é um Wookiee do planeta Kashyyyk.",
    "R2-D2 nunca teve sua memória apagada nas trilogias.",
    "C-3PO é fluente em mais de seis milhões de formas de comunicação.",
    "O planeta natal de Luke é Tatooine.",
    "Leia é irmã gêmea de Luke Skywalker.",
    "Han Solo pilotava a Millennium Falcon.",
    "Obi-Wan Kenobi foi mestre de Anakin Skywalker.",
    "Anakin virou Darth Vader após cair para o lado sombrio.",
    "O Império Galáctico foi formado por Palpatine.",
    "Palpatine também era conhecido como Darth Sidious.",
    "O sabre de luz vermelho é associado aos Sith.",
    "Mace Windu usava um sabre de luz roxo.",
    "O planeta natal dos Jedi é Ilum (mais tarde transformado na Starkiller Base).",
    "Jar Jar Binks é um Gungan de Naboo.",
    "A batalha de Hoth ocorre no episódio V.",
    "O retorno dos Jedi é o episódio VI.",
    "Kylo Ren é filho de Leia e Han Solo.",
    "Rey foi treinada por Luke e Leia.",
    "O General Grievous colecionava sabres de luz Jedi.",
    "O Conde Dookan foi mestre de Qui-Gon Jinn.",
    "Qui-Gon Jinn treinou Obi-Wan Kenobi.",
    "Yoda se exilou em Dagobah após a Ordem 66.",
    "A Ordem 66 foi o comando que levou à morte de milhares de Jedi.",
    "Clones foram criados no planeta Kamino.",
    "Boba Fett é um clone não modificado de Jango Fett.",
    "Jango Fett foi o modelo genético do exército clone.",
    "Anakin perdeu seu braço em combate com Conde Dookan.",
    "O sabre de luz de Luke foi originalmente de Anakin.",
    "Leia foi a primeira princesa da galáxia a liderar uma rebelião.",
    "Lando Calrissian era o administrador da Cidade das Nuvens.",
    "A Millennium Falcon completou o percurso de Kessel em menos de 12 parsecs.",
    "Darth Maul usava um sabre de luz de lâmina dupla.",
    "Darth Maul sobreviveu após ser partido ao meio por Obi-Wan.",
    "Grogu é o nome verdadeiro do bebê Yoda.",
    "Din Djarin é o nome do Mandaloriano.",
    "Bo-Katan Kryze liderou os Mandalorianos em Mandalore.",
    "O Darksaber é um símbolo de liderança em Mandalore.",
    "O senador Bail Organa criou a Aliança Rebelde.",
    "A Nova República foi formada após a queda do Império.",
    "A Primeira Ordem surgiu dos remanescentes do Império.",
    "Snoke era um clone manipulado por Palpatine.",
    "Palpatine retornou no episódio IX através de clonagem.",
    "Luke Skywalker fundou uma nova escola Jedi.",
    "Ben Solo destruiu a nova escola Jedi de Luke.",
    "A Resistência foi formada para combater a Primeira Ordem.",
    "A Aliança Rebelde venceu na Batalha de Endor.",
    "Os Ewoks ajudaram os rebeldes em Endor.",
    "O planeta Coruscant é o centro político da galáxia.",
    "Padmé Amidala era senadora e mãe de Luke e Leia.",
    "Obi-Wan usou a Força para enganar stormtroopers: “These aren’t the droids you’re looking for.”",
    "Stormtroopers têm pontaria notoriamente ruim.",
    "Os Jawas são nativos de Tatooine e negociam sucata.",
    "Tusken Raiders também vivem em Tatooine.",
    "Luke aprendeu a usar a Força com Obi-Wan e Yoda.",
    "Rey construiu seu próprio sabre de luz amarelo.",
    "O sabre amarelo representa o equilíbrio dos Jedi Sentinelas.",
    "O Império usava TIE Fighters como naves principais.",
    "Os X-Wings são as naves dos rebeldes.",
    "O planeta Mustafar é onde Anakin virou Vader.",
    "Darth Vader construiu um castelo em Mustafar.",
    "O sabre de luz de Rey tem uma empunhadura giratória.",
    "Chopper é um dos droides protagonistas da série Rebels.",
    "Ahsoka Tano foi padawan de Anakin.",
    "Ahsoka deixou a Ordem Jedi por discordâncias éticas.",
    "O Almirante Thrawn é um dos vilões mais estratégicos da saga.",
    "A série *Andor* mostra a origem da rebelião pela perspectiva de Cassian.",
    "Cassian Andor roubou os planos da Estrela da Morte.",
    "K-2SO era um dróide imperial reprogramado por Cassian.",
    "Rogue One mostra os eventos logo antes do episódio IV.",
    "O general Hux traiu a Primeira Ordem em favor da Resistência.",
    "Maz Kanata ajudou Rey a encontrar o sabre de Anakin.",
    "A Força pode ser usada para controlar mentes.",
    "O sabre de luz requer um cristal kyber para funcionar.",
    "Cristais kyber são sensíveis à Força.",
    "Kyber corrompido por um Sith fica vermelho.",
    "Darth Plagueis era o mestre de Palpatine.",
    "A Força tem dois lados: o luminoso e o sombrio.",
    "O treinamento Jedi começa desde criança.",
    "Jedi não podem ter laços emocionais fortes.",
    "Anakin se casou secretamente com Padmé.",
    "O Mestre Jedi Ki-Adi-Mundi sobreviveu à Ordem 66 por um tempo.",
    "Shaak Ti morreu durante o ataque ao Templo Jedi.",
    "O planeta Naboo é o lar de Padmé e Jar Jar.",
    "Watto era o comerciante que possuía Anakin como escravo.",
    "Anakin construiu o C-3PO quando era criança.",
    "A Pod Race em Tatooine foi vencida por Anakin.",
    "General Hux era filho de Brendol Hux, fundador do programa de crianças-soldado.",
    "A Aliança Rebelde se originou em segredo durante a República.",
    "A série *Rebels* conecta eventos entre os episódios III e IV.",
    "Sabine Wren era uma Mandaloriana que manipulava o Darksaber.",
    "Ezra Bridger desapareceu junto com Thrawn ao fim de *Rebels*.",
    "Luke enfrentou seu pai em *O Retorno de Jedi*.",
    "A batalha de Geonosis marcou o início das Guerras Clônicas.",
    "Os clones tinham chips de controle instalados.",
    "Rex, clone comandante, removeu seu chip com ajuda de Ahsoka.",
    "Cody, outro clone importante, atirou em Obi-Wan na Ordem 66.",
    "A série *The Bad Batch* mostra clones modificados sobrevivendo após a queda da República.",
    "Grogu foi treinado no Templo Jedi antes do Império.",
    "Luke treinou Grogu brevemente após os eventos de *The Mandalorian* temporada 2.",
    "Boba Fett assumiu o trono de Jabba em Tatooine.",
    "O rancor é a criatura usada por Jabba para executar prisioneiros.",
    "Salacious B. Crumb é o pequeno bicho risonho do trono de Jabba."
]

# Rota raiz
@app.route('/')
def home():
    return "API Star Wars - Acesse /fact para um fato aleatório."

# Rota para retornar um fato aleatório
@app.route('/fact')
def fact():
    return jsonify(fact=random.choice(facts))

# Inicia o servidor Flask se este arquivo for executado diretamente
if __name__ == '__main__':
    app.run(debug=True)
